---
- name: Configure wg1
  notify: Wg1_restart
  block:
    - name: Copy WG1 iface config template
      ansible.builtin.template:
        src: wg1.j2
        dest: /etc/wireguard/wg1.conf
        mode: '600'

    - name: Add WG1 Oregon clients info
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg1.conf
        block: "{{ lookup('template', 'files/wg1_oregon.conf') }}"
      when: ansible_hostname == "oregon"

    - name: Add WG1 Nuremberg clients info
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg1.conf
        block: "{{ lookup('template', 'files/wg1_nuremberg.conf') }}"
      when: ansible_hostname == "nuremberg"

    - name: Add WG1 Katowice clients info
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg1.conf
        block: "{{ lookup('template', 'files/wg1_katowice.conf') }}"
      when: ansible_hostname == "katowice"

    - name: Add WG1 MSK clients info
      ansible.builtin.blockinfile:
        path: /etc/wireguard/wg1.conf
        block: "{{ lookup('template', 'files/wg1_msk.conf') }}"
      when: ansible_hostname == "msk"
