---
name: Syntax
run-name: ${{ github.actor }} is testing out Ansible Role
on: [push]
jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Ansible modules
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip -y
          pip3 install ansible ansible-lint yamllint molecule
      - name: Molecule test
        run: molecule test 
